import React, { useState, useEffect, useRef } from 'react';
import '../index.css';

const API_URL = "http://127.0.0.1:8000/predict"; // ✅ Correct FastAPI endpoint

// 🧠 Local heuristic fallback
function localHeuristicDetect(text) {
  const words = text.trim().split(/\s+/).filter(Boolean);
  const sentences = text.split(/[.!?]/).filter(s => s.trim().length > 0);

  const aiIndicators = [/as an AI/i, /as an AI language model/i, /I am an AI/i, /generated by/i, /training data/i];
  const foundIndicator = aiIndicators.some(rx => rx.test(text));

  const repetitiveness = computeNgramDupRate(text, 3);
  const punctuationRate = (text.match(/[.!?]/g) || []).length / Math.max(1, sentences.length);
  const avgWordLen = words.length ? words.reduce((s, w) => s + w.length, 0) / words.length : 0;
  const perplexityScore = computePerplexity(text);

  let score = 0.2;
  score += Math.min(0.6, repetitiveness * 1.5);
  score += Math.min(0.2, (1 - punctuationRate) * 0.5);
  score += Math.min(0.2, perplexityScore * 0.4);
  if (foundIndicator) score = Math.max(score, 0.9);
  if (avgWordLen > 5.5) score -= 0.08;
  if (punctuationRate > 0.1) score -= 0.08;
  score = Math.max(0, Math.min(1, score));

  const label = score >= 0.6 ? 'AI' : 'Human';
  const explanation = `Heuristic score=${score.toFixed(2)}; repetitiveness=${repetitiveness.toFixed(2)}; avgWordLen=${avgWordLen.toFixed(2)}; punctuationRate=${punctuationRate.toFixed(3)}; perplexity=${perplexityScore.toFixed(2)}.`;

  return {
    label,
    score,
    explanation,
    signals: {
      repetitiveness,
      punctuationRate,
      avgWordLen,
      indicator: foundIndicator,
      perplexityScore
    }
  };
}

function computePerplexity(text) {
  const words = text.toLowerCase().split(/\s+/).filter(Boolean);
  const wordCounts = {};
  words.forEach(word => {
    wordCounts[word] = (wordCounts[word] || 0) + 1;
  });
  let totalLogProb = 0;
  words.forEach(word => {
    const prob = wordCounts[word] / words.length;
    totalLogProb += Math.log(prob);
  });
  const perplexity = Math.exp(-totalLogProb / words.length);
  return Math.min(1, Math.max(0, 1 - (perplexity / 100)));
}

function computeNgramDupRate(text, n = 3) {
  const words = text.toLowerCase().replace(/[^\w\s]/g, ' ').split(/\s+/).filter(Boolean);
  if (words.length < n) return 0;
  const ngrams = new Map();
  let total = 0;
  for (let i = 0; i <= words.length - n; i++) {
    const gram = words.slice(i, i + n).join(' ');
    ngrams.set(gram, (ngrams.get(gram) || 0) + 1);
    total++;
  }
  let duplicates = 0;
  for (const count of ngrams.values()) {
    if (count > 1) duplicates += count - 1;
  }
  return total === 0 ? 0 : duplicates / total;
}

function ProgressPieChart({ score = 0, label = 'Unknown' }) {
  const aiPct = Math.round((score ?? 0) * 100);
  const chartStyle = { '--ai-percentage': `${aiPct}%` };
  return (
    <div className={`progress-pie-chart ${label.toLowerCase()}`} style={chartStyle}>
      <div className="label">
        <h3>{aiPct}%</h3>
        <span>{label === 'AI' ? 'AI Score' : 'Human Score'}</span>

      </div>
    </div>
  );
}

function SignalRow({ name, value = 0, invert = false, description }) {
  let v = Number(value) || 0;
  if (v > 1) v = Math.min(1, (v - 1) / 7);
  const pct = Math.round(Math.max(0, Math.min(1, v)) * 100);
  const displayPct = invert ? 100 - pct : pct;
  return (
    <div className="signal-row" title={description || name}>
      <div className="signal-meta">
        <div className="signal-name">{name}</div>
        <div className="signal-value muted">{pct}%</div>
      </div>
      <div className="signal-bar">
        <div className="signal-fill" style={{ width: `${displayPct}%` }} />
      </div>
      <small className="muted signal-desc">{description}</small>
    </div>
  );
}

export default function Detector() {
  const [text, setText] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [history, setHistory] = useState([]);
  const fileInputRef = useRef(null);
  const resultPanelRef = useRef(null);

  useEffect(() => {
    const saved = window.localStorage.getItem('detector_history_v2');
    if (saved) setHistory(JSON.parse(saved));
  }, []);

  useEffect(() => {
    window.localStorage.setItem('detector_history_v2', JSON.stringify(history));
  }, [history]);

  function handleFileChange(e) {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = ev => setText(String(ev.target.result));
    reader.onerror = () => alert('Could not read file');
    reader.readAsText(file);
  }

  async function runDetection() {
    if (!text.trim()) {
      alert('Please paste or enter some text to analyze.');
      return;
    }
    setLoading(true);
    setResult(null);

    try {
      let out;
      const resp = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text })
      });

      if (!resp.ok) throw new Error(`API returned ${resp.status}`);
      const data = await resp.json();

      // ✅ Match backend response structure
      out = {
        label: data.prediction || 'Unknown',
        score: typeof data.confidence === 'number' ? data.confidence : null,
        explanation: `Entropy: ${data.entropy?.toFixed(3)} | Words: ${data.word_count}`,
        signals: {
          repetitiveness: data.probabilities?.AI ?? 0,
          punctuationRate: data.entropy ?? 0,
          perplexityScore: data.probabilities?.Human ?? 0,
          indicator: data.prediction === 'AI'
        }
      };

      out.timestamp = new Date().toISOString();
      out.fullText = text;
      setResult(out);
      setHistory(h => [{ id: Date.now(), ...out }, ...h].slice(0, 50));
      resultPanelRef.current.scrollIntoView({ behavior: 'smooth' });
    } catch (err) {
      console.error(err);
      alert('Detection failed: ' + (err.message || err));
    } finally {
      setLoading(false);
    }
  }

  function clearAll() {
    setText('');
    setResult(null);
  }

  function clearHistory() {
    if (window.confirm('Clear all history?')) setHistory([]);
  }

  const aiPct = result?.label === 'AI'
  ? Math.round((result?.score ?? 0) * 100)
  : Math.round(100 - (result?.score ?? 0) * 100)
const humanPct = 100 - aiPct


  return (
    <div className="detector enhanced">
      <section className="panel input-panel">
        <div className="panel-head">
          <h2>Analyze Text</h2>
          <div className="panel-actions">
            <label className="file-input file-btn">
              <input ref={fileInputRef} type="file" accept=".txt" onChange={handleFileChange} />
              📎 Upload
            </label>
            <button className="secondary" onClick={clearAll}>🧹 Clear</button>
          </div>
        </div>
        <textarea
          className="text-area"
          placeholder="Paste or write text to analyze..."
          value={text}
          onChange={e => setText(e.target.value)}
          rows={12}
        />
        <div className="controls">
          <button className="primary" onClick={runDetection} disabled={loading}>
            {loading ? 'Analyzing…' : 'Run Detection'}
          </button>
          <div className="muted help">
            <strong>Mode:</strong> Backend (FastAPI)
          </div>
        </div>
      </section>

      <section ref={resultPanelRef} className="panel result-panel">
        {!result ? (
          <div className="empty">
            <p className="muted">Press <strong>Run Detection</strong> to start analysis.</p>
          </div>
        ) : (
          <div className="result-grid no-preview">
            <div className="gauge-wrap">
              <ProgressPieChart score={result.score ?? 0} label={result.label} />
              <div className="gauge-summary">
                <span className={`gauge-chip ${result.label === 'AI' ? 'ai' : 'human'}`}>{result.label}</span>
                <span className="gauge-pct">
  {result.label === 'AI'
    ? `${aiPct}% AI / ${humanPct}% Human`
    : `${humanPct}% Human / ${aiPct}% AI`}
</span>

              </div>
            </div>
            <div className="signals">
              <SignalRow name="Repetitiveness" value={result.signals?.repetitiveness ?? 0} />
              <SignalRow name="Entropy" value={result.signals?.punctuationRate ?? 0} />
              <SignalRow name="Perplexity" value={result.signals?.perplexityScore ?? 0} />
              <SignalRow name="AI Indicator" value={result.signals?.indicator ? 1 : 0} />
            </div>
            <div className="explain">
              <pre className="muted small">{result.explanation}</pre>
              <small className="muted">Analyzed at {new Date(result.timestamp).toLocaleString()}</small>
            </div>
          </div>
        )}
      </section>
    </div>
  );
}
